version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      gomod-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directories:
      - /
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
