name: CI

on:
  pull_request:
  push:

jobs:
  unittest:
    uses: na4ma4/actions/.github/workflows/unit-test.yml@main

  goreleaser:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - unittest
    uses: na4ma4/actions/.github/workflows/goreleaser.yml@main
    secrets:
      token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
